#!/usr/bin/env python
# encoding: utf-8
"""
Macros_To_Py_Script.py

To run open Macros_To_Py_Script.py in fiji and click run. 

Shows how to conduct basic Fiji stripting in python.  These set of commands were generated using the macro recorder in Fiji.  Most commands generated by the macro recorder can be traslated into a python command by simply adding 'IJ.' to the front, however this will not work for all commands. Also, this is not ideal for large data sets.  For maximum efficiency, the python stript should be written by manipulating Fiji's internal data structures rather than using the functions generated by the macro recorder. ( See http://www.ini.uzh.ch/~acardona/fiji-tutorial/ for more details. )

Final Notes: Fiji is a application running on the Java virtual machine.  Therefore, when Fiji uses a python script it is actually running on a python language interpreter that operates inside the java virtual machine.  This has its limitations because presently Java can only run Python 2.5 (see Jython for more details).

"""

import sys
import os

from ij import IJ

dir_path= "/Users/richardhart/Dropbox/AMRE/"
file_name="2013-08-03-96dpiPrintTesting-DifferentZheights-Sample.png"

def main():
	IJ.open(dir_path+file_name)  #IJ.open("/Users/richardhart/Dropbox/AMRE/2013-08-03-96dpiPrintTesting-DifferentZheights-Sample.png")
	IJ.selectWindow(file_name) #IJ.selectWindow("2013-08-03-96dpiPrintTesting-DifferentZheights-Sample.png")
	IJ.run("Options...", "iterations=1 count=1 edm=Overwrite")
	IJ.run("Make Binary")
	IJ.run("Watershed")
	IJ.run("Set Measurements...", "area mean standard modal min centroid center perimeter bounding fit shape feret's integrated median skewness kurtosis area_fraction stack redirect=None decimal=3")
	IJ.run("Analyze Particles...", "size=0-Infinity circularity=0.00-1.00 show=Ellipses display clear include")
	IJ.selectWindow("Results")
	IJ.saveAs("Results", dir_path + "Results.txt"); #IJ.saveAs("/Users/richardhart/Dropbox/AMRE/Results.txt")

if __name__ == '__main__':
	main()

